openapi: 3.0.0
info:
  title: Movie app
  version: 1.0.0
  description: Document for myApi
servers:
  - url: "http://localhost:3000" #
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    refreshToken:
      type: apiKey
      in: header
      name: x-rtoken-id
      description: Client ID for authentication
tags:
  - name: Access
    description: "User access management endpoints"

paths: {} # Bắt đầu với một đối tượng rỗng
